# Generated by Django 3.2.4 on 2022-03-24 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220324_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['name'], 'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
    ]
