# Generated by Django 3.2.4 on 2022-03-24 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_genero_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_ciudad', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='api.ciudad')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_pais', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='api.pais')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_departamento',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='api.departamento'),
        ),
        migrations.CreateModel(
            name='Avistamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('nota', models.CharField(max_length=200)),
                ('latitud', models.CharField(max_length=50)),
                ('longitud', models.CharField(max_length=50)),
                ('id_especie', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='api.especie')),
                ('id_lugar', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='api.lugar')),
            ],
            options={
                'verbose_name': 'Avistamiento',
                'verbose_name_plural': 'Avistamientos',
                'ordering': ['name'],
            },
        ),
    ]
