# Generated by Django 3.2.4 on 2022-03-24 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220324_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avistamiento',
            name='id_especie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.especie'),
        ),
        migrations.AlterField(
            model_name='avistamiento',
            name='id_lugar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.lugar'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='id_departamento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.departamento', unique=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='id_pais',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.pais'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='id_clase',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.clase'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='id_familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.familia'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='id_filo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.filo'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='id_genero',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.genero'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='id_orden',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.orden'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='id_ciudad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.ciudad', unique=True),
        ),
    ]
